name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy Backend
      env:
        DEPLOY_SERVER_USER: ${{ secrets.DEPLOY_SERVER_USER }}
        DEPLOY_SERVER_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
        DEPLOY_SERVER_SECRET: ${{ secrets.DEPLOY_SERVER_SECRET }}
      run: |
        sshpass -p "$DEPLOY_SERVER_SECRET" ssh -o StrictHostKeyChecking=no $DEPLOY_SERVER_USER@$DEPLOY_SERVER_HOST << EOF
          export TMPDIR='/var/tmp' 
          mkdir app; cd app
          mkdir tft-double-up; cd tft-double-up
          git clone https://github.com/cosminpm/tft-double-up.git
        EOF
